apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "producer"
        dapr.io/port: "8081"
        dapr.io/log-as-json: "true"
        dapr.io/config: "tracing"
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/"
    spec:
      containers:
      - name: producer
        image: mchmarny/producer:v0.5.2
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8081"
        - name: DAPR_HTTP_PORT
          value: "3500"
        - name: PRODUCER_STATE_STORE_NAME
          value: producer-state
        - name: PRODUCER_RESULT_TOPIC_NAME
          value: tweets
        - name: TW_CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              name: pipeline-twitter
              key: consumer-key
        - name: TW_CONSUMER_SECRET
          valueFrom:
            secretKeyRef:
              name: pipeline-twitter
              key: consumer-secret
        - name: TW_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: pipeline-twitter
              key: access-token
        - name: TW_ACCESS_SECRET
          valueFrom:
            secretKeyRef:
              name: pipeline-twitter
              key: access-secret

