apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: positive-tweets
spec:
  type: pubsub.redis
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: negative-tweets
spec:
  type: pubsub.redis
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""