apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: tweets
  labels:
    app: tweets
    group: pipeline
spec:
  type: pubsub.azure.servicebus
  metadata:
  - name: connectionString
    secretKeyRef:
      name: pipeline-bus
      key: connection-string
